DB_USERNAME = "root"
DB_PASSWORD = "Password"
DB_HOST = "127.0.0.1"
DB_PORT = "3306"
DB_NAME = "stock_trading"

SQLALCHEMY_DATABASE_URI = (f"mysql+pymysql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = "your-secret-key"
